In [1]:
import cv2
import numpy as np
face_cascade = cv2.CascadeClassifier('C:\opencv\opencv\sources\data\haarcascades\haarcascade_frontalface_default.xml')


In [18]:
face_coordinates = []
def recognise_faces(faces):
    for face in faces:
        img = cv2.imread(face)
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        faces = face_cascade.detectMultiScale(gray, 1.035,5)
        face_coordinates.append(faces)
        print(len(faces), faces)
        for (x,y,w,h) in faces:
            img = cv2.rectangle(img, (x,y), (x+w, y+h), (255,0,0), 2) 
        cv2.imshow('img',img)
        cv2.waitKey(0)
        cv2.destroyAllWindows()

In [19]:
#faces = ['faces/1.jpg','faces/2.jpg','faces/3.jpg','faces/4.jpg','faces/5.jpg','faces/6.jpg','faces/7.jpg','faces/8.jpg',]
faces = ['faces.jpg']
recognise_faces(faces)
        

63 [[  16  440   57   57]
 [ 342  308   71   71]
 [ 331  444   68   68]
 [ 668  729   64   64]
 [ 126  446   65   65]
 [ 464  445   63   63]
 [ 255  305   61   61]
 [ 667  307   62   62]
 [ 446   21   60   60]
 [ 884  445   68   68]
 [ 237  450   64   64]
 [ 344  166   65   65]
 [ 990  320   59   59]
 [ 546  452   66   66]
 [ 675  455   63   63]
 [ 234  722   66   66]
 [ 779  454   60   60]
 [ 666  174   62   62]
 [ 998  724   65   65]
 [ 345  728   60   60]
 [ 885  172   65   65]
 [ 891  730   65   65]
 [ 115  727   68   68]
 [ 551  729   67   67]
 [ 886   27   63   63]
 [  15  733   70   70]
 [ 127  309   64   64]
 [ 448  309   62   62]
 [  14  166   73   73]
 [ 244  169   68   68]
 [ 559  302   63   63]
 [ 898  307   61   61]
 [  15  306   67   67]
 [ 446  159   78   78]
 [ 779  573   76   76]
 [ 125   27   65   65]
 [ 779  167   77   77]
 [ 452  719   77   77]
 [ 771   24   72   72]
 [ 230   23   72   72]
 [ 358   26   63   63]
 [ 560   26   72   72]
 [ 776  728   69   69]
 [ 997  